import Head from 'next/head';
import styles from '../styles/Kanban.module.css';
import { useTransitoryItemsData } from '../customHooks/transitoryItemsHook';
import { ConvertToXLSX } from '../utils/convertToXls';
import { AddItem } from '../components/addItem';
import { DownloadDataButton } from '../components/downloadDataButton';
import { ItemCard } from '../components/itemCard';
import { NewRowContainer } from '../components/newRowContainer';



const Swimlane = ({ statusArray, handleDragOver, handleDragStart, handleDrop, getItemsCallback, priorityFilter, updateTaskDescription }) => {
  const handleColumnDrop = (event, status) => {
    handleDrop(event, status, priorityFilter);
  };

  return (
    <>
      {statusArray.map((status) => (
        <KanbanColumn
          key={status.status}
          status={status.status}
          handleDragOverCallback={handleDragOver}
          handleDropCallback={handleColumnDrop}

        >
          {getItemsCallback(status.status, priorityFilter).map((todo) => (
            <ItemCard key={todo.id} item={todo} dragCallback={handleDragStart} updateItemDescription={updateTaskDescription} />
          ))}
        </KanbanColumn>
      ))}
    </>
  );
};

const KanbanColumn = ({
  children,
  columnTitle,
  status,
  handleDragOverCallback,
  handleDropCallback,
}) => {
  return (
    <div
      className={styles.column}
      onDragOver={handleDragOverCallback}
      onDrop={(event) => handleDropCallback(event, status)}
    >
      <h2>{columnTitle}</h2>
      <div className={styles.cards}>
        {children}
      </div>
    </div>
  );
};

const HeadingColumn = ({
  columnTitle,

}) => {
  return (
    <div
      className={styles.headingColumn}

    >
      <h2>{columnTitle}</h2>

    </div>
  );
};

const PriorityColumn = ({
  columnTitle,

}) => {

  let conditionalStyles = styles.priorityColumn

  if (columnTitle === "") {
    conditionalStyles = styles.blankCell
  }



  return (
    <div
      className={conditionalStyles}

    >
      <h2>{columnTitle}</h2>

    </div>
  );
};


const HeadingSwimLane = (statusArray) => {

  return (
    <>
      {statusArray.statusArray.map((status) => (
        <HeadingColumn
          key={status.status}
          columnTitle={status.name}
        >

        </HeadingColumn>
      ))}
    </>
  );
};


export default function KanbanBoard({ endpoint }) {

  const [todos, addTask, updateTaskDescription, handleStatusUpdate] = useTransitoryItemsData(`http://localhost:3001/${endpoint}`)

  const kanbanProperties = {
    statuses: [
      { status: 'blocked', name: 'Blocked' },
      { status: 'todo', name: 'To Do' },
      { status: 'in-progress', name: 'In Progress' },
      { status: 'approvals', name: 'In Approvals' },
      { status: 'done', name: 'Done' }
    ],
    priorities: [
      { priority: 1, name: 'Must Have' },
      { priority: 2, name: 'Should Have' },
      { priority: 3, name: 'Could Have' },
      { priority: 4, name: "Won't Have" }
    ]
  }

  const handleDownloadClick = ({ data, filename }) => {
    ConvertToXLSX({ data, filename });
  };



  const getColumnTodos = (status, priority) => {
    const columnTodos = todos.filter((todo) => todo.status === status && todo.priority === priority);
    return columnTodos;
  };

  const handleDragStart = (event, todo) => {
    event.dataTransfer.setData('text/plain', JSON.stringify(todo));
  };

  const handleDragOver = (event) => {
    event.preventDefault();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>MOSCOW Kanban Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Kanban Board</h1>
        <DownloadDataButton handleDownloadClick={() => handleDownloadClick({ data: todos, filename: "myData" })} />

        <AddItem addItemCallback={addTask} endpoint="workItems" itemType={{ type: "Task" }} />

        <div className={styles.kanban}>
          <NewRowContainer>
            <PriorityColumn columnTitle="" />
            <HeadingSwimLane
              statusArray={kanbanProperties.statuses}
            />
          </NewRowContainer>
          {kanbanProperties.priorities.map((priority) => (
            <NewRowContainer>
              <PriorityColumn columnTitle={priority.name} />
              <Swimlane
                key={priority.priority}
                statusArray={kanbanProperties.statuses}
                handleDragOver={handleDragOver}
                handleDrop={handleStatusUpdate}
                handleDragStart={handleDragStart}
                getItemsCallback={getColumnTodos}
                priorityFilter={priority.priority}
                updateTaskDescription={updateTaskDescription}
              />
            </NewRowContainer>
          ))}
        </div>

      </main>

    </div>
  );
}


